<img src="https://i0.wp.com/amanxai.com/wp-content/uploads/2022/08/Password-Strength-Checker-with-Machine-Learning.png?resize=1200%2C675&ssl=1"/>

## Password Strenght Checker

## How to Create a Password Strength Checker?
A password strength checker works by understanding the combination of digits, letters, and special symbols you use in your password. It is created by training a machine learning model on a labelled dataset of different combinations of letters and special symbols people use in passwords. The model learns from data about what combinations of letters and symbols can be classified as a solid or weak password.

In [27]:
import pandas as pd
import re
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [28]:
df = pd.read_csv(
    "Data\PWS_Check.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

In [29]:
df.head()

      password strength;;;;
0     kzde5577        1;;;;
1     kino3434        1;;;;
2    visi7k1yr        1;;;;
3     megzy123        1;;;;
4  lamborghin1        1;;;;

In [30]:
df["strength"] = df["strength;;;;"].astype(str).str.replace(r";.*", "", regex=True)

In [31]:
df = df.drop("strength;;;;", axis=1)

In [32]:
df.head()

      password strength
0     kzde5577        1
1     kino3434        1
2    visi7k1yr        1
3     megzy123        1
4  lamborghin1        1

In [33]:
df = df.dropna(subset=["password"])
df["password"] = df["password"].astype(str)

In [36]:
import math
from collections import Counter

def entropy(password):
    counts = Counter(password)
    length = len(password)
    return -sum((c/length) * math.log2(c/length) for c in counts.values())

In [37]:
# ------------------------
# 2. FEATURE ENGINEERING
# ------------------------
def extract_features(password):
    password = str(password)

    return [
        len(password),
        int(bool(re.search(r"[A-Z]", password))),
        int(bool(re.search(r"[a-z]", password))),
        int(bool(re.search(r"[0-9]", password))),
        int(bool(re.search(r"[!@#$%^&*(),.?\":{}|<>]", password))),
        entropy(password)  
    ]
X = df["password"].apply(extract_features).tolist()
y = df["strength"]

In [38]:
# ------------------------
# 3. TRAIN
# ------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.9997237300917664

In [26]:
# ------------------------
# 4. MODEL KAYDET
# ------------------------
joblib.dump(model, "PWS_Model.pkl")

print("Model kaydedildi ✅")

Model kaydedildi ✅

## Summarry 

I also use other security levels controls in HuggingFace code 

In conclusion, this project demonstrates how machine learning can be applied to cybersecurity problems such as password evaluation.

The system provides fast and useful feedback to users, helping them create stronger and more secure passwords. Future improvements may include integrating rule-based checks and expanding the dataset for higher accuracy.